use_frameworks!

platform :ios, '12.0'

target 'WBLEPrinterService_Example' do
  pod 'WBLEPrinterService', :path => '../'

  target 'WBLEPrinterService_Tests' do
    inherit! :search_paths

    
  end
end
